# Generated by Selenium IDE
from lib2to3.pytree import Base
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import datetime


PATH = "C:\chromedriver_win32\chromedriver.exe"
# driver = webdriver.Chrome(PATH)
hoje = datetime.datetime.now()
dd = hoje.day
mm = hoje.month
aa = hoje.year
data = str(dd)+'/'+str(mm)+'/'+str(aa)



driver = webdriver.Chrome(PATH)

driver.get("http://www.imprensaoficial.com.br/#"+data) #colocar o dia de hj
driver.set_window_size(1900, 980)
driver.find_element(By.ID, "content_txtPalavrasChave").click()
driver.find_element(By.ID, "content_txtPalavrasChave").send_keys("\"Raul Cruz Nadim\"")
driver.find_element(By.ID, "content_btnBuscar").click()
driver.find_element_by_class_name("joyride-close-tip").click()
driver.find_element(By.ID, "content_lnkOrderByData").click()

#pega a data da última públicação
data_publi_elem = driver.find_element(By.ID, "content_dtgResultado_lblData_0")
data_publi = data_publi_elem.get_attribute('innerHTML')
print(data_publi)
#pega a data da última publicação

driver.quit()



